In [1]:
#Importing useful libraries
import tensorflow as tf
import keras
import numpy as np
import pandas as pd

Using TensorFlow backend.


In [2]:
#Loading the dataset
train = pd.read_csv("Twitter Classification/Train.csv")
test = pd.read_csv("Twitter Classification/Test.csv")

In [3]:
train.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [4]:
test.head()

id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [5]:
train["label"].value_counts()

0    29720
1     2242
Name: label, dtype: int64

In [6]:
Y = pd.get_dummies(train["label"]).values #one-hot encoding for labels

In [7]:
X = train['tweet']

In [8]:
X.shape #There are 31962 training examples

(31962,)

In [9]:
X_test = test['tweet']

In [10]:
all = X.append(X_test, ignore_index=True) #Combining train and test data

In [11]:
#Removing '@user' from all the tweets
import re

for i in range(X.shape[0]) :
    r = re.findall("@user", str(all[i]))
    for j in r :
        all[i] = re.sub(j,'',str(all[i]))

In [12]:
#Removing punctuations, numbers and special characters
all = all.str.replace("[^a-zA-Z#]", " ")

In [13]:
#Removing hashtag. For eg:- '#happy' will be converted to 'happy'
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j[:1] == '#':
            new_string = new_string.strip() + ' ' + j[1:]
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string

In [14]:
#Dealing with some common abbreviations

for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'u':
            new_string = new_string.strip() + ' ' + 'you'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
        
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'ur':
            new_string = new_string.strip() + ' ' + 'your'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'y':
            new_string = new_string.strip() + ' ' + 'why'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string

for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'r':
            new_string = new_string.strip() + ' ' + 'are'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'k':
            new_string = new_string.strip() + ' ' + 'okay'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'm':
            new_string = new_string.strip() + ' ' + 'am'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    

for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'b4':
            new_string = new_string.strip() + ' ' + 'before'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
        
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'ty':
            new_string = new_string.strip() + ' ' + 'thank you'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'bc':
            new_string = new_string.strip() + ' ' + 'because'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string

for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'grt':
            new_string = new_string.strip() + ' ' + 'great'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'gud':
            new_string = new_string.strip() + ' ' + 'good'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'h8':
            new_string = new_string.strip() + ' ' + 'hate'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'bday':
            new_string = new_string.strip() + ' ' + 'birthday'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
        
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'wtf':
            new_string = new_string.strip() + ' ' + 'hate'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'wth':
            new_string = new_string.strip() + ' ' + 'hate'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string

for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'idgaf':
            new_string = new_string.strip() + ' ' + 'hate'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'n':
            new_string = new_string.strip() + ' ' + 'and'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
    
for i in range(all.shape[0]) :
    new_string = ''
    for j in str(all[i]).split() :
        if j == 'luv':
            new_string = new_string.strip() + ' ' + 'love'
        else :
            new_string = new_string.strip() + ' ' + j
    all[i] = new_string
        



In [15]:
#Dealing with spelling mistakes and replacing them with possible words.

from symspellpy.symspellpy import SymSpell

dictionary_path = "dictionary.txt"
sym_spell = SymSpell(2, 7)
sym_spell.load_dictionary(dictionary_path, 0, 1)


for i in range(all.shape[0]) :
    result = sym_spell.lookup_compound(all[i],2)
    all[i] = result[0].term

In [16]:
#Transformed dataset
all[0:5]

0    when a father is dysfunctional and is so selfi...
1    thanks for left credit i can to use cause they...
2                                  by day your majesty
3    model i love you take with you all the time in...
4                    fact guide society now motivation
Name: tweet, dtype: object

In [17]:
#Importing more libraries for tokenizing and other operations
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [18]:
t = Tokenizer()
t.fit_on_texts(all)
vocab_size = len(t.word_index) + 1
encoded = t.texts_to_sequences(all)
print(encoded)

[[41, 2, 51, 11, 11798, 7, 11, 22, 3315, 46, 8358, 114, 236, 266, 114, 9753, 397], [166, 10, 310, 2089, 4, 34, 1, 424, 742, 44, 75, 1, 1722, 8359, 6693, 8, 3020, 834, 53, 8360], [27, 13, 23, 3021], [141, 4, 15, 5, 87, 20, 5, 21, 3, 38, 8, 23], [549, 1827, 1468, 54, 269], [1120, 552, 5174, 7, 201, 775, 275, 44, 419, 4234, 7, 176, 15636, 41, 44, 53, 90, 15637], [2193, 130, 4514], [3, 157, 233, 147, 11, 3, 147, 10, 2090, 34, 1, 142, 63, 25, 233, 2090, 169, 1377, 902, 32, 2256, 233, 99], [30, 285, 15, 3, 995, 3022, 858, 3316, 1598, 1598, 7411], [692, 105, 4, 17, 12, 2, 22, 68], [1209, 3474, 1435, 2144, 327, 7412, 52, 1182, 1, 8, 167, 138, 191, 183, 229], [30, 24, 22, 3315, 88, 486, 88, 1694, 284, 88, 284, 1943, 1005, 3315, 46, 796, 3023, 15], [4, 53, 1, 67, 14, 442, 48, 95, 209, 1599], [34, 1623, 4795, 1653, 233, 1469, 3, 1480, 8361, 1944], [49, 1470, 8, 1298, 1193, 1624, 373, 1147, 220, 4008, 3, 2911, 220, 4008], [4235, 1723, 11, 271, 102, 1723, 5, 625, 466], [4, 17, 59, 10, 262, 2, 1083,

In [19]:
#Since every sentence has different length,zero is padded to reach the maximum length(25)
padded = pad_sequences(encoded, maxlen=25, padding='post')
print(padded)

[[   41     2    51 ...     0     0     0]
 [  166    10   310 ...     0     0     0]
 [   27    13    23 ...     0     0     0]
 ...
 [  613 25281    48 ...     0     0     0]
 [   28    31    83 ...     0     0     0]
 [   14   399    22 ...     0     0     0]]


In [20]:
X = padded[:31962]
X_test = padded[31962:]

In [21]:
#Preparing the embedding layer by using pretrained glove embeddings.
embeddings_index = dict()
f = open('glove.6B.100d.txt', encoding="utf8")
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

In [22]:
embedding_matrix = np.zeros((vocab_size, 100))
for word, i in t.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [23]:
#Splitting the dataset into Training and Cross Validation set
from sklearn.model_selection import train_test_split
X_train, X_csv, Y_train, Y_csv = train_test_split(X, Y, test_size=0.10,random_state = 5,stratify = Y)

In [24]:
from keras.layers import Embedding, Flatten, Dense, LSTM, Dropout
from keras.models import Sequential

In [25]:
#Defining our F1 score metric

from keras import backend as K

def f1(y_true, y_pred):
    y_pred = K.round(y_pred)
    tp = K.sum(K.cast(y_true*y_pred, 'float'), axis=0)
    tn = K.sum(K.cast((1-y_true)*(1-y_pred), 'float'), axis=0)
    fp = K.sum(K.cast((1-y_true)*y_pred, 'float'), axis=0)
    fn = K.sum(K.cast(y_true*(1-y_pred), 'float'), axis=0)

    p = tp / (tp + fp + K.epsilon())
    r = tp / (tp + fn + K.epsilon())

    f1 = 2*p*r / (p+r+K.epsilon())
    f1 = tf.where(tf.is_nan(f1), tf.zeros_like(f1), f1)
    return K.mean(f1)

In [26]:
#Using ModelCheckpoint so that we do not have to worry about overfitting due to training for too many epochs
from keras.callbacks import ModelCheckpoint
filepath="tc.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_f1', save_best_only=True, mode='max')
callbacks_list = [checkpoint]

In [27]:
#Model

model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length = 25, trainable=True)
model.add(e)
model.add(LSTM(128,activation = 'tanh', return_sequences=True))
model.add(Dropout(0.4))
model.add(LSTM(128,activation = 'tanh', return_sequences=False))
model.add(Dropout(0.4))
model.add(Dense(2, activation = 'sigmoid'))

In [28]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['acc',f1])

In [29]:
model.fit(X_train, Y_train, epochs = 50, batch_size = 1024,callbacks = callbacks_list,validation_data=(X_csv,Y_csv))

Train on 28765 samples, validate on 3197 samples
Epoch 1/50
28765/28765 [==============================] - 16s 570us/step - loss: 0.3305 - acc: 0.9230 - f1: 0.4811 - val_loss: 0.2572 - val_acc: 0.9299 - val_f1: 0.4818
Epoch 2/50
28765/28765 [==============================] - 14s 503us/step - loss: 0.2608 - acc: 0.9298 - f1: 0.4818 - val_loss: 0.2540 - val_acc: 0.9299 - val_f1: 0.4818
Epoch 3/50
28765/28765 [==============================] - 14s 502us/step - loss: 0.2562 - acc: 0.9298 - f1: 0.4818 - val_loss: 0.2420 - val_acc: 0.9299 - val_f1: 0.4818
Epoch 4/50
28765/28765 [==============================] - 15s 506us/step - loss: 0.2019 - acc: 0.9338 - f1: 0.5788 - val_loss: 0.1497 - val_acc: 0.9446 - val_f1: 0.7663
Epoch 5/50
28765/28765 [==============================] - 15s 507us/step - loss: 0.1344 - acc: 0.9517 - f1: 0.7954 - val_loss: 0.1258 - val_acc: 0.9496 - val_f1: 0.7869
Epoch 6/50
28765/28765 [==============================] - 15s 505us/step - loss: 0.1050 - acc: 0.9621 - f1

Epoch 49/50
28765/28765 [==============================] - 15s 506us/step - loss: 0.0021 - acc: 0.9995 - f1: 0.9980 - val_loss: 0.3009 - val_acc: 0.9562 - val_f1: 0.8354
Epoch 50/50
28765/28765 [==============================] - 15s 507us/step - loss: 0.0015 - acc: 0.9997 - f1: 0.9990 - val_loss: 0.3277 - val_acc: 0.9564 - val_f1: 0.8382


In [30]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 100)           2528400   
_________________________________________________________________
lstm_1 (LSTM)                (None, 25, 128)           117248    
_________________________________________________________________
dropout_1 (Dropout)          (None, 25, 128)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 258       
Total params: 2,777,490
Trainable params: 2,777,490
Non-trainable params: 0
_________________________________________________________________


In [31]:
#Loading the weights which performed best on validation data considering f1 score.
model.load_weights("tc.best.hdf5")

In [32]:
Pred = model.predict(X_test)

In [33]:
Pred = np.argmax(Pred,axis = 1)
print(Pred.reshape((17197,1)))

[[0]
 [1]
 [0]
 ...
 [0]
 [0]
 [0]]


In [34]:
sub = pd.DataFrame({'id':test['id'],'label':Pred})
sub.to_csv('TC.csv',index=False)

In [35]:
at = model.evaluate(X_train,Y_train)[1]
acsv = model.evaluate(X_csv,Y_csv)[1]

3197/3197 [==============================] - 3s 998us/step


In [36]:
print("Training set accuracy:- ",at*100)
print("Cross validation set accuracy:- ",acsv*100)

Training set accuracy:-  99.38293064488093
Cross validation set accuracy:-  96.70003126254483


Test set f1 score :- 0.70788